data:
  id_image: "${hydra:runtime.cwd}/demo_file/Iron_man.jpg"
  att_image: "none"
  specific_id_image: "none"
  att_video: "${hydra:runtime.cwd}/demo_file/multi_people_1080p.mp4"
  output_dir: ${hydra:runtime.cwd}/output
  clean_work_dir: True

pipeline:
  face_detector_weights: "${hydra:runtime.cwd}/weights/face_detector_scrfd_10g_bnkps.onnx"
  face_id_weights: "${hydra:runtime.cwd}/weights/arcface_net.jit"
  parsing_model_weights: "${hydra:runtime.cwd}/weights/79999_iter.pth"
  simswap_weights: "${hydra:runtime.cwd}/weights/simswap_224_latest_net_G.pth"
  gfpgan_weights: "${hydra:runtime.cwd}/weights/GFPGANv1.4_ema.pth"
  blend_module_weights: "${hydra:runtime.cwd}/weights/blend_module.jit"
  device: "cuda"
  crop_size: 224
  # it seems that the official 224 checkpoint works better with 'none' face alignment type
  checkpoint_type: "official_224" #"none"
  face_alignment_type: "none" #"ffhq"
  smooth_mask_iter: 7
  smooth_mask_kernel_size: 17
  smooth_mask_threshold: 0.9
  face_detector_threshold: 0.6
  specific_latent_match_threshold: 0.05
  enhance_output: True

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .